### Import Necessary Libraries

In [163]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

1.12.1
False


# PyTorch warmup

### 1. Use torch.randn to create two tensors of size (29, 30, 32) and (32, 100)

In [164]:
tensor_a = torch.randn(29, 30, 32)
print('Tensor of Size (29, 30, 32): \n' , tensor_a)

tensor_b = torch.randn(32, 100)
print('Tensor of Size (32, 100): \n' , tensor_b)

Tensor of Size (29, 30, 32): 
 tensor([[[-1.3273e-01, -1.7137e-03,  2.3768e-01,  ...,  8.7736e-01,
           9.9803e-01,  1.5487e+00],
         [-7.8726e-01, -3.3921e-01,  8.3773e-01,  ..., -4.8650e-01,
           1.6367e+00,  8.9340e-01],
         [-1.5818e-02, -4.3789e-01,  1.3492e+00,  ...,  4.9213e-01,
          -2.3609e-01, -5.7800e-01],
         ...,
         [ 1.6923e+00, -6.1207e-02,  1.3573e+00,  ...,  1.8294e+00,
          -6.2201e-01, -2.5485e+00],
         [-1.4159e+00,  2.0194e+00, -8.1503e-01,  ..., -9.1955e-01,
          -3.3892e-01, -1.2415e+00],
         [-1.0451e+00, -3.0325e-01, -1.4625e+00,  ...,  7.9478e-01,
          -7.4056e-01,  5.7179e-01]],

        [[ 7.6344e-02,  1.2227e+00, -2.9117e-01,  ...,  1.7126e+00,
           6.5116e-01,  3.5459e-02],
         [ 1.3650e+00, -8.8486e-01, -8.0388e-01,  ..., -3.9080e-01,
           7.6656e-01, -1.0701e+00],
         [ 2.8774e-01, -1.9205e+00,  5.7871e-02,  ...,  3.4832e-01,
          -1.5781e+00,  4.5148e-01],
        

### 2. Use  torch.matmul  to matrix multiply the two tensors

In [165]:
product = torch.matmul(tensor_a, tensor_b)
print('Product of tensor_a and tensor_b: \n' , product)

print('Shape of Tensor: ' , product.shape)

Product of tensor_a and tensor_b: 
 tensor([[[ -0.3658,   4.0343,  -8.5939,  ...,  -1.0294,   0.6143,  11.5574],
         [  1.8736,   2.3378,  -5.2487,  ...,  -5.5383,  -5.2335,  -0.3518],
         [  4.6152,   5.2167,   6.0129,  ...,   9.1791,  -3.6223,   4.9273],
         ...,
         [-10.0908,   2.3655,   0.9489,  ...,   5.1504,  -6.2577,  -1.6819],
         [ -2.1101,  -0.1993,  -2.9200,  ...,   5.3591,   4.2625,   3.9612],
         [  0.3956,  14.5996,  -3.5194,  ...,   4.4043,   3.7146,  -3.2771]],

        [[-10.0672,  -0.5467,  -0.0804,  ...,  -0.0164,   3.8181,  -1.3932],
         [  5.8277,  -9.0610,  -3.6578,  ...,   7.0324,  -4.6470,   2.5972],
         [  7.6433,   2.6269,  -4.5265,  ...,   5.9333,   1.9873,   1.4495],
         ...,
         [ -4.6386,   1.0373,  -2.2187,  ...,  -7.5864,   6.0699,   6.1841],
         [ -5.8824,  -2.9219,  -0.2697,  ...,  -4.1298,   0.0664,   2.7122],
         [ -5.8216,  -5.5138,  -8.5588,  ...,   7.4204,  -7.1499,   6.4899]],

        

### 3. What is the difference between torch.matmul , torch.mm , torch.bmm , and torch.einsum , and the @ operator?

### 4. Use torch.sum on the resulting tensor, passing the optional argument of dim=1 to sum across the 1st dimension. Before you run this, can you predict the size?

In [166]:
tensor_sum = torch.sum(product, dim = 1)
print('Sum of Tensor across 1st Dimension: \n' , tensor_sum)

print('Shape of Tensor: ' , tensor_sum.shape)

Sum of Tensor across 1st Dimension: 
 tensor([[ 30.6956, -30.5862,   9.6243,  ...,   9.5548,  21.0395,  46.9285],
        [ -7.2162, -24.5919, -10.7819,  ...,  50.1187,  23.1065,  30.1112],
        [ 13.0457,  53.7973, -44.9612,  ...,  32.0453, -23.2937,  48.4604],
        ...,
        [ 19.1404,  -5.7801, -81.3716,  ...,  11.1412, -47.7008,   1.6392],
        [ 15.1754,  30.8802,   6.2086,  ...,  17.5357,  24.6202,  20.4633],
        [ 53.6354,  -1.9531,   5.9686,  ...,   2.8311,  30.3693,  59.3527]])
Shape of Tensor:  torch.Size([29, 100])


### 5. Create a new long tensor of size  (3, 10)

In [167]:
long_tensor = torch.ones((3, 10), dtype = torch.long)
print('Long Tensor: \n' , long_tensor)

long_tensor[0, 0] = 2
long_tensor[1, 2] = 4
long_tensor[2, 4] = 6

print('Updated Long Tensor: \n' , long_tensor)

Long Tensor: 
 tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
Updated Long Tensor: 
 tensor([[2, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 4, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 6, 1, 1, 1, 1, 1]])


### 6. Use this new long tensor to index into the tensor from step 2

In [168]:
indexed_tensor = product[long_tensor]
print('Indexed Tensor: \n' , indexed_tensor)

print('Shape of Tensor: ' , indexed_tensor.shape)

Indexed Tensor: 
 tensor([[[[ -3.8154,  11.2351,  -0.2199,  ...,   0.5313,  -6.6225,  -5.5016],
          [ -1.0206,   1.8529,  -6.1232,  ...,   0.3614, -13.0106,   0.5022],
          [ -0.7371,   4.3845,  -0.3101,  ...,  -4.9942,   4.9844,  -0.2857],
          ...,
          [ -1.2104,   2.2662,  -2.9051,  ...,  -0.1920,  -6.0320,   1.6292],
          [ -6.3490,  -6.0993,  -0.6012,  ...,   6.1687,  -2.1058,  -0.7258],
          [ -9.6136,  -1.6007,  -0.4758,  ...,   1.6273,  -7.7952,  -7.7196]],

         [[-10.0672,  -0.5467,  -0.0804,  ...,  -0.0164,   3.8181,  -1.3932],
          [  5.8277,  -9.0610,  -3.6578,  ...,   7.0324,  -4.6470,   2.5972],
          [  7.6433,   2.6269,  -4.5265,  ...,   5.9333,   1.9873,   1.4495],
          ...,
          [ -4.6386,   1.0373,  -2.2187,  ...,  -7.5864,   6.0699,   6.1841],
          [ -5.8824,  -2.9219,  -0.2697,  ...,  -4.1298,   0.0664,   2.7122],
          [ -5.8216,  -5.5138,  -8.5588,  ...,   7.4204,  -7.1499,   6.4899]],

         [[-

### 7. Use  torch.mean  to average across the last dimension in the tensor from step 6

In [172]:
mean_tensor = torch.mean(indexed_tensor, dim = 3)
print(mean_tensor)

print('Shape of Tensor: ' , mean_tensor.shape)

tensor([[[-1.3454, -0.2317, -0.0933,  0.4291, -0.1312,  1.3061,  0.5642,
           1.1304,  0.1062,  0.1260, -0.2958,  0.1313, -0.5186,  0.8559,
           0.8028,  0.1708,  0.1969, -0.9095, -0.1092, -0.0769,  0.0858,
           0.1287, -0.2001,  0.1188, -0.2245,  0.3429, -0.2672, -0.7560,
          -0.2014, -0.2246],
         [-0.1650, -1.0124,  0.5759, -0.2350, -1.0106,  0.3657, -0.2067,
           0.0975,  0.2823, -0.8947,  0.7574,  0.1022, -0.7763,  0.0437,
           0.1217,  0.8906, -0.8341,  0.2223,  0.4081, -0.7304,  0.6348,
          -0.2456,  1.1863, -0.2763,  0.5241,  0.0163,  0.4372,  0.6273,
           1.1752, -0.1575],
         [-0.1650, -1.0124,  0.5759, -0.2350, -1.0106,  0.3657, -0.2067,
           0.0975,  0.2823, -0.8947,  0.7574,  0.1022, -0.7763,  0.0437,
           0.1217,  0.8906, -0.8341,  0.2223,  0.4081, -0.7304,  0.6348,
          -0.2456,  1.1863, -0.2763,  0.5241,  0.0163,  0.4372,  0.6273,
           1.1752, -0.1575],
         [-0.1650, -1.0124,  0.5759, 

### 8. Redo step 2. on the GPU and compare results from step 2

In [180]:
tensor_a_cuda = tensor_a.to(device = 'cuda')
tensor_b_cuda = tensor_b.to(device = 'cuda')
product_gpu = torch.matmul(tensor_a, tensor_b)
print('Product of tensor_a and tensor_b on GPU: \n' , product_gpu)

print('Shape of Tensor: ' , product_gpu.shape)

AssertionError: Torch not compiled with CUDA enabled

### 9. Write a pure PyTorch program to compute the value of  up to 4 decimal places without using the square root or other math functions from any of the libraries. 
### Hint: Notice that the answer is the (positive) root of the equation, $$𝑥^2 −2 = 0$$ 
### To find the root, you might want to use "Newton's Method": $$𝑥_{𝑛+1} = 𝑥_{𝑛} − \frac{𝑓(𝑥)}{𝑓′(𝑥)}$$


# Fail-fast prototyping

When building neural networks, you want things to either work or fail fast. Long iteration loops are 
the worst enemy of a machine learning practitioner. \
For e.g., while writing code, you might want to incrementally test your code by doing something 
like this:

batch_size = 32 \
num_features = 512 \
embedding_size = 16

\# construct a dummy input \
x = torch.randn(batch_size, num_features)

\# we want to project the input to embedding_size \
fc = torch.nn.Linear(num_features, embedding_size)

\# test if that works \
print(fc(x).shape)

# Fail-fast exercises

### 1. [Glove](https://nlp.stanford.edu/projects/glove/) has 300 dimension embeddings. Design an nn.Module that takes a sentence of max_len words, tokenizes words by spaces, represents the sentence by averaging the glove embeddings of constituent words. What is the shape of the resulting sentence embedding? When you implement this, you will need to make some assumptions. What are they?