## Import Necessary Libraries

In [11]:
import torch
import numpy as np

### 1. Use torch.randn to create two tensors of size (29, 30, 32) and (32, 100)

In [12]:
tensor_a = torch.randn(29, 30, 32)
print(f'Tensor of Size (29, 30, 32): \n' , tensor_a)

tensor_b = torch.randn(32, 100)
print(f'Tensor of Size (32, 100): \n' , tensor_b)

Tensor of Size (29, 30, 32): 
 tensor([[[-7.7589e-01, -1.3676e+00,  3.9482e-01,  ...,  5.5299e-02,
          -1.4245e+00, -1.3087e+00],
         [ 1.0706e+00, -7.8943e-01,  7.3748e-02,  ..., -3.4567e-01,
          -1.8387e-01,  6.6235e-01],
         [-8.4642e-01,  3.0006e-01,  8.9392e-02,  ..., -9.3400e-01,
           4.5202e-02,  2.9408e+00],
         ...,
         [ 6.9961e-01, -1.4005e+00, -2.9609e-01,  ...,  3.8532e-01,
          -8.6415e-01, -3.8906e-01],
         [ 1.1973e+00, -1.2059e+00,  8.0195e-01,  ...,  1.5786e-01,
           1.6190e+00, -2.8515e-01],
         [ 2.9069e-01,  1.0007e+00, -8.5468e-01,  ...,  2.0680e-01,
          -7.6256e-01,  5.9658e-02]],

        [[-3.5339e-02,  1.1503e+00, -4.9757e-01,  ...,  1.4863e+00,
          -3.7370e-01, -1.3828e+00],
         [-1.1466e+00, -1.7388e+00,  2.5176e-01,  ..., -3.2575e-02,
          -8.5138e-01,  2.0757e-01],
         [ 4.4972e-01, -1.4172e+00,  2.9934e+00,  ...,  4.1633e-02,
           2.1380e-01, -1.3970e-01],
        

### 2. Use  torch.matmul  to matrix multiply the two tensors

In [13]:
product = torch.matmul(tensor_a, tensor_b)
print(f'Product of tensor_a and tensor_b: \n' , product)

Product of tensor_a and tensor_b: 
 tensor([[[ -4.8295,   4.4617,   5.0124,  ...,  -2.7486,  -4.8893,   0.4758],
         [ -8.6769,   3.4888,   1.8577,  ...,   3.6953,   4.2130,   0.5280],
         [  8.7911,  -1.5192,  -3.2885,  ...,  -4.2186,  -2.7789,  -4.9724],
         ...,
         [ -6.3541,   3.5343,   4.0439,  ...,  -2.2165,   4.4525,  -1.2472],
         [  5.9284,   5.5188,  -1.0182,  ...,  -4.3804,   5.4490,   5.2763],
         [ -6.5147,  -6.1992,  -6.2879,  ...,  -6.2811,   5.9539,   3.3518]],

        [[ -0.5348,  -6.3662,   6.9988,  ...,  -5.7621,   5.6306,   4.5977],
         [  0.4723,   8.5068,  -7.2660,  ...,  -9.4194,  -3.2013,  -2.3016],
         [ -8.3949,   2.3782,  -0.9244,  ...,   5.5035,  -3.7476,   4.1259],
         ...,
         [  8.5506,   3.5643,  -2.2010,  ...,   7.3285,  -4.0881,  -5.3084],
         [  5.6947,  -3.5312,   0.4335,  ...,  11.3806,   1.7332,   1.3753],
         [  8.0289,   0.2485,   5.3024,  ...,  -0.4243,   5.2594,  -6.2395]],

        

### 3. What is the difference between torch.matmul , torch.mm , torch.bmm , and torch.einsum , and the @ operator?

### 4. Use torch.sum on the resulting tensor, passing the optional argument of dim=1 to sum across the 1st dimension. Before you run this, can you predict the size?

In [40]:
tensor_sum = torch.sum(product, dim = 1)
print(f'Sum of Tensor across 1st Dimension: \n' , tensor_sum)

tensor_sum_size = tensor_sum.shape
print(f'Shape of Tensor: ' , tensor_sum_size)

Sum of Tensor across 1st Dimension: 
 tensor([[-39.2603, -18.4487,  -8.6800,  ...,   1.0446,  27.0830,   1.8920],
        [ 48.9014,  52.3975,  11.5064,  ...,   3.6752, -27.4597,   4.9161],
        [-10.3217,  62.4027, -28.6632,  ...,   9.3006, -76.3959, -22.4609],
        ...,
        [-50.8766, -18.5695,  -8.6986,  ...,  13.3157,  10.5833,  18.0345],
        [ 19.0812, -24.2235,   1.1324,  ...,   2.9980,  61.7706,  18.0880],
        [-32.5161, -14.0122,  15.3174,  ...,  25.2751,  -7.1284,   4.5847]])
Shape of Tensor:  torch.Size([29, 100])


### 5. Create a new long tensor of size  (3, 10)

In [36]:
new_tensor = torch.randn(3, 10)
print(f'New Tensor: \n' , new_tensor)

New Tensor: 
 tensor([[-0.6383,  1.1944, -0.7550, -0.5168,  1.9056,  0.7147,  0.2119,  1.4441,
         -0.5423,  1.4227],
        [ 0.1597, -0.7162,  1.5685,  1.3753, -0.0318, -0.6219, -1.4754,  0.6837,
          0.1019, -0.4290],
        [ 0.4510, -2.0713, -1.8031, -1.0698, -0.4906, -0.5042,  0.6149,  0.9900,
          1.7283, -0.3987]])


### 6. Use this new long tensor to index into the tensor from step 2