# Import Necessary Libraries

In [2]:
import torch
import torchtext
print(torch.__version__)
print(torchtext.__version__)


1.13.1
0.14.1


# Set device as GPU if available

In [75]:
if torch.cuda.is_available():
    dev = 'cuda'
elif torch.backends.mps.is_available():
    dev = 'mps'
else:
    dev = 'cpu'
device = torch.device(dev)    
print(f'Device: {device}')

Device: mps


# PyTorch warmup

### 1. Use torch.randn to create two tensors of size (29, 30, 32) and (32, 100)

In [4]:
tensor_a = torch.randn(29, 30, 32)
print('Tensor of Size (29, 30, 32): \n' , tensor_a)

tensor_b = torch.randn(32, 100)
print('Tensor of Size (32, 100): \n' , tensor_b)

Tensor of Size (29, 30, 32): 
 tensor([[[-1.2669e+00, -5.6959e-01, -1.7969e+00,  ...,  1.8188e+00,
           9.7032e-01,  1.5106e+00],
         [ 6.6902e-01, -4.5929e-02, -5.6820e-01,  ..., -3.7463e-02,
          -8.2540e-01, -4.4991e-01],
         [-7.3153e-01,  3.6122e-02,  9.2934e-01,  ...,  1.5369e+00,
          -3.8756e-01, -1.2843e+00],
         ...,
         [ 1.0068e+00, -2.0352e+00, -1.0178e-01,  ...,  1.3100e+00,
          -1.0394e+00,  2.6688e-01],
         [ 2.2937e+00, -9.4478e-01,  9.5343e-01,  ...,  3.3338e-01,
           1.0328e+00, -9.9259e-01],
         [ 1.2945e+00,  2.1403e+00, -6.1383e-01,  ...,  7.5230e-01,
           7.0326e-01,  3.5825e-01]],

        [[-1.2154e+00, -1.6357e+00,  4.5557e-02,  ...,  1.7509e-01,
           1.1140e+00, -4.1342e-01],
         [-1.6959e-01,  7.1065e-01, -1.8802e+00,  ..., -1.2577e-01,
          -5.9885e-01, -9.0522e-01],
         [ 1.9752e-01, -4.7546e-01,  3.2681e-01,  ..., -5.9618e-01,
          -1.2522e+00,  2.1489e-01],
        

### 2. Use  torch.matmul  to matrix multiply the two tensors

In [5]:
product = torch.matmul(tensor_a, 
                       tensor_b)
print('Product of tensor_a and tensor_b: \n' , product)

print('Shape of Tensor: ' , product.shape)

Product of tensor_a and tensor_b: 
 tensor([[[-13.2621,   9.3731, -11.7893,  ...,  -7.3152,  11.6473,  -6.2425],
         [  1.6365,  -3.0511,   2.1437,  ...,   1.7488,  -6.4826,  -3.2745],
         [ -5.7323,   2.4026,   5.0012,  ...,   2.1264,   1.2310,   7.0712],
         ...,
         [  1.7914,  -0.2842,  -0.6901,  ...,   7.1259,  -8.9405,  -0.2058],
         [ -7.0371,   2.5656,   5.3010,  ...,   2.4419, -14.7984,   0.6097],
         [ -6.4793,  -5.5452,   6.9085,  ...,  -0.6199,  -7.2145, -11.2881]],

        [[  1.3306,   3.9205,   0.2360,  ...,   6.2160,   4.7269,   2.5456],
         [ -2.1774,  -3.2473,  -2.5274,  ...,   3.5847,  -2.9077,   2.0045],
         [  3.4768,   1.0987,  -4.0413,  ...,   2.4075,  -7.9049,  -3.2112],
         ...,
         [  2.3400,  -6.5402,  -4.7628,  ...,   8.0365,  -5.0185,   2.6872],
         [  7.7205,  -5.6621,  -4.2838,  ...,  -2.6443,  -5.1610,   4.8454],
         [ -3.1295,   5.9888,   2.1850,  ...,  -1.1024,   4.8072,  -3.6004]],

        

### 3. What is the difference between torch.matmul , torch.mm , torch.bmm , and torch.einsum , and the @ operator?

1. torch.matmul() ->
2. torch.mm() ->
3. torch.bmm() ->
4. torch.einsum() ->
5. @ operator -> It is a shorthand for the torch.matmul() function.

### 4. Use torch.sum on the resulting tensor, passing the optional argument of dim=1 to sum across the 1st dimension. Before you run this, can you predict the size?

In [7]:
tensor_sum = torch.sum(product, 
                       dim = 1)
print('Sum of Tensor across 1st Dimension: \n' , tensor_sum)

print('Shape of Tensor: ' , tensor_sum.shape)

Sum of Tensor across 1st Dimension: 
 tensor([[   4.2655,  -76.7089,  -49.9342,  ...,   14.1479,  -32.9342,
           -1.1706],
        [  28.3876,    1.3230,   10.2586,  ...,   34.6930,   12.5124,
           41.9824],
        [ -91.3736,   67.1420, -106.7556,  ...,  -32.7357,   62.9556,
          -32.1673],
        ...,
        [ -15.1692,   33.4527,   27.5558,  ...,  -13.5718,   -8.8082,
          -24.9549],
        [  22.2288,   38.7153,  -16.8282,  ...,  -21.3191,    2.6734,
           -9.2732],
        [ -15.7508,   28.8513,   16.5797,  ...,   -8.1515,   31.8660,
           34.4739]])
Shape of Tensor:  torch.Size([29, 100])


### 5. Create a new long tensor of size  (3, 10)

In [8]:
long_tensor = torch.ones((3, 10), 
                         dtype = torch.long)
print('Long Tensor: \n' , long_tensor)

long_tensor[0, 0] = 2
long_tensor[1, 2] = 4
long_tensor[2, 4] = 6

print('Updated Long Tensor: \n' , long_tensor)

Long Tensor: 
 tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
Updated Long Tensor: 
 tensor([[2, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 4, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 6, 1, 1, 1, 1, 1]])


### 6. Use this new long tensor to index into the tensor from step 2

In [9]:
indexed_tensor = product[long_tensor]
print('Indexed Tensor: \n' , indexed_tensor)

print('Shape of Tensor: ' , indexed_tensor.shape)

Indexed Tensor: 
 tensor([[[[ -7.4345,  14.9439,  -2.7215,  ...,  -0.5436,  14.2772,   5.2867],
          [ -7.5322,   2.3207,   2.3941,  ...,   3.0348,  -5.0813,   2.7684],
          [ -6.3394,  -1.6578, -15.2204,  ...,  -2.6148,  -5.7177,  -5.8000],
          ...,
          [  0.3471,   0.5292,  -0.0286,  ...,  -2.2514,  10.0249,  -1.1148],
          [ -1.6198,   1.6737,  -5.8284,  ...,   5.0135,   5.6666,   5.0532],
          [ -4.8812,   3.6147,  -4.2578,  ...,  -1.2021,   6.5086,  -3.4150]],

         [[  1.3306,   3.9205,   0.2360,  ...,   6.2160,   4.7269,   2.5456],
          [ -2.1774,  -3.2473,  -2.5274,  ...,   3.5847,  -2.9077,   2.0045],
          [  3.4768,   1.0987,  -4.0413,  ...,   2.4075,  -7.9049,  -3.2112],
          ...,
          [  2.3400,  -6.5402,  -4.7628,  ...,   8.0365,  -5.0185,   2.6872],
          [  7.7205,  -5.6621,  -4.2838,  ...,  -2.6443,  -5.1610,   4.8454],
          [ -3.1295,   5.9888,   2.1850,  ...,  -1.1024,   4.8072,  -3.6004]],

         [[ 

### 7. Use  torch.mean  to average across the last dimension in the tensor from step 6

In [10]:
mean_tensor = torch.mean(indexed_tensor, 
                         dim = 3)
print(mean_tensor)

print('Shape of Tensor: ' , mean_tensor.shape)

tensor([[[ 0.6802,  0.1478, -0.4493,  0.5894, -0.2018, -0.3625, -0.0960,
          -0.0247, -0.1436, -0.6260, -0.2898, -1.0251, -0.8783, -0.6275,
           0.8946, -0.2514, -0.2000,  0.4910, -0.9260, -0.1619, -0.6153,
           0.1295, -0.4846,  0.0144,  0.1611, -0.2952,  0.0742,  0.5718,
          -0.5532,  0.2340],
         [ 0.2324, -0.4181, -0.0926, -0.2284, -0.4701,  0.0532, -0.2603,
           0.8504,  0.1164,  0.2217,  0.2363,  0.6357, -0.4133, -0.0121,
           0.3394, -0.3771,  0.0648,  0.0354,  0.2620, -0.5153, -0.4681,
           0.6021,  0.2546, -0.7532, -0.1000, -0.6862,  0.3918,  0.0464,
           0.2880,  0.6022],
         [ 0.2324, -0.4181, -0.0926, -0.2284, -0.4701,  0.0532, -0.2603,
           0.8504,  0.1164,  0.2217,  0.2363,  0.6357, -0.4133, -0.0121,
           0.3394, -0.3771,  0.0648,  0.0354,  0.2620, -0.5153, -0.4681,
           0.6021,  0.2546, -0.7532, -0.1000, -0.6862,  0.3918,  0.0464,
           0.2880,  0.6022],
         [ 0.2324, -0.4181, -0.0926, 

### 8. Redo step 2. on the GPU and compare results from step 2

In [11]:
tensor_a_cuda = tensor_a.to(device = device)
tensor_b_cuda = tensor_b.to(device = device)
product_gpu = torch.matmul(tensor_a, tensor_b)
print('Product of tensor_a and tensor_b on GPU: \n' , product_gpu)

print('Shape of Tensor: ' , product_gpu.shape)

Product of tensor_a and tensor_b on GPU: 
 tensor([[[-13.2621,   9.3731, -11.7893,  ...,  -7.3152,  11.6473,  -6.2425],
         [  1.6365,  -3.0511,   2.1437,  ...,   1.7488,  -6.4826,  -3.2745],
         [ -5.7323,   2.4026,   5.0012,  ...,   2.1264,   1.2310,   7.0712],
         ...,
         [  1.7914,  -0.2842,  -0.6901,  ...,   7.1259,  -8.9405,  -0.2058],
         [ -7.0371,   2.5656,   5.3010,  ...,   2.4419, -14.7984,   0.6097],
         [ -6.4793,  -5.5452,   6.9085,  ...,  -0.6199,  -7.2145, -11.2881]],

        [[  1.3306,   3.9205,   0.2360,  ...,   6.2160,   4.7269,   2.5456],
         [ -2.1774,  -3.2473,  -2.5274,  ...,   3.5847,  -2.9077,   2.0045],
         [  3.4768,   1.0987,  -4.0413,  ...,   2.4075,  -7.9049,  -3.2112],
         ...,
         [  2.3400,  -6.5402,  -4.7628,  ...,   8.0365,  -5.0185,   2.6872],
         [  7.7205,  -5.6621,  -4.2838,  ...,  -2.6443,  -5.1610,   4.8454],
         [ -3.1295,   5.9888,   2.1850,  ...,  -1.1024,   4.8072,  -3.6004]],

 

### 9. Write a pure PyTorch program to compute the value of $\sqrt{2}$ up to 4 decimal places without using the square root or other math functions from any of the libraries. 
### Hint: Notice that the answer is the (positive) root of the equation, $$𝑥^2 −2 = 0$$ 
### To find the root, you might want to use "Newton's Method": $$𝑥_{𝑛+1} = 𝑥_{𝑛} − \frac{𝑓(𝑥)}{𝑓′(𝑥)}$$


# Fail-fast prototyping

When building neural networks, you want things to either work or fail fast. Long iteration loops are 
the worst enemy of a machine learning practitioner. \
For e.g., while writing code, you might want to incrementally test your code by doing something 
like this:

batch_size = 32 \
num_features = 512 \
embedding_size = 16

\# construct a dummy input \
x = torch.randn(batch_size, num_features)

\# we want to project the input to embedding_size \
fc = torch.nn.Linear(num_features, embedding_size)

\# test if that works \
print(fc(x).shape)

# Fail-fast exercises

### 1. [Glove](https://nlp.stanford.edu/projects/glove/) has 300 dimension embeddings. Design an nn.Module that takes a sentence of max_len words, tokenizes words by spaces, represents the sentence by averaging the glove embeddings of constituent words. What is the shape of the resulting sentence embedding? When you implement this, you will need to make some assumptions. What are they?

In [78]:
# Load GloVe Embeddings
from torchtext.vocab import GloVe

GLOVE_DIM = 300
glove = GloVe(name = '840B', 
              dim = GLOVE_DIM)

print(f'Loaded {len(glove.itos)} words present in GloVe')

embeddings_tensor = glove.vectors
embeddings_tensor = embeddings_tensor.to(device = device)

Loaded 2196017 words present in GloVe


In [79]:
NUM_SENT = 512
sents = list()
for i in range(NUM_SENT):
    sents.append('This is the quest zero and it has a deadline this Sunday, March 29')
print(len(sents))

512


In [84]:
import torch.nn as nn

class GloveEmbeddingAvg(nn.Module):
    
    def __init__(self, max_len):
        super().__init__()
        self.max_len = max_len
        self.embedding = nn.Embedding.from_pretrained(embeddings_tensor)
        
    def forward(self, 
                sent):
        # Tokenize the sentence by spaces
        tokens = sent.split(' ')[:self.max_len]
        # Get idx of each token from the GloVe dictionary
        glove_dict_indexes = [glove.stoi[token] for token in tokens]
        # Convert it into Tensor
        glove_dict_indexes = torch.tensor(glove_dict_indexes, 
                                          device = device)
        # Get Word Embeddings for all tokens
        word_embeds = self.embedding(glove_dict_indexes)
        # Sentence Embedding = Average of Word Embeddings
        sent_embeds = word_embeds.mean(dim = 0)
        return sent_embeds.view(1, -1)

MAX_LEN = 10
glove_embeds_avg = GloveEmbeddingAvg(MAX_LEN).to(device)

print(glove_embeds_avg(sents[0]).shape)
print(glove_embeds_avg(sents[0]))

torch.Size([1, 300])
tensor([[-4.5604e-02,  1.7180e-01, -8.1301e-02,  4.7771e-02, -1.2547e-02,
         -1.1558e-01, -7.5017e-03, -1.1177e-01,  3.8822e-02,  2.2306e+00,
         -1.5930e-01, -5.0211e-02, -1.2576e-01,  3.9923e-02, -1.0560e-01,
         -1.7879e-01,  3.3900e-03,  1.1905e+00, -1.3859e-01,  2.1556e-02,
         -5.3867e-02, -1.2833e-01,  6.1120e-02, -3.2409e-02,  8.4664e-02,
          8.9627e-02, -8.6490e-02, -8.3099e-02, -1.1932e-01, -2.4925e-02,
         -4.4643e-02,  7.1976e-02,  3.5064e-02, -2.2729e-02,  9.1324e-02,
          4.1020e-03,  8.5674e-02, -4.3367e-02,  1.2036e-03, -2.2725e-01,
          1.6723e-01,  2.0299e-01,  1.5572e-01, -1.5584e-01,  7.3151e-02,
         -3.7005e-02, -1.9181e-01,  7.4557e-02, -1.4330e-01,  1.1176e-01,
          8.2322e-03,  1.8108e-01, -4.9120e-02, -2.9479e-02,  4.8363e-02,
          5.6336e-02,  2.6151e-02,  7.5750e-02,  1.1126e-01, -2.0988e-01,
         -9.6492e-02,  6.5016e-02,  2.9249e-02,  1.1692e-01,  6.9829e-02,
         -1.8340e

### 2. How will you modify step 1. so that the sentence embeddings are in $R^{50}$ ?
BONUS: Can you think of more than one way to do this? What are the implications of each method?

In [86]:
class GloveEmbeddingAvg_50_Dim(nn.Module):
    
    def __init__(self, max_len):
        super().__init__()
        self.max_len = max_len
        self.embedding = nn.Embedding.from_pretrained(embeddings_tensor)
        self.fc = nn.Linear(GLOVE_DIM, 50)
        
    def forward(self, 
                sent):
        # Tokenize the sentence by spaces
        tokens = sent.split(' ')[:self.max_len]
        # Get idx of each token from the GloVe dictionary
        glove_dict_indexes = [glove.stoi[token] for token in tokens]
        # Convert it into Tensor
        glove_dict_indexes = torch.tensor(glove_dict_indexes, 
                                          device = device)
        # Get Word Embeddings for all tokens
        word_embeds = self.embedding(glove_dict_indexes)
        # Sentence Embedding = Average of Word Embeddings
        sent_embeds = word_embeds.mean(dim = 0)
        return self.fc(sent_embeds.view(1, -1))

MAX_LEN = 10
glove_embeds_avg_50_dim = GloveEmbeddingAvg_50_Dim(MAX_LEN).to(device)

print(glove_embeds_avg_50_dim(sents[0]).shape)
print(glove_embeds_avg_50_dim(sents[0]))

torch.Size([1, 50])
tensor([[ 0.2243, -0.0319,  0.1634,  0.1289,  0.0428, -0.0822,  0.0282, -0.0104,
         -0.1254,  0.0005,  0.0542, -0.0879, -0.0224,  0.0221, -0.0661,  0.0089,
         -0.1289,  0.0929, -0.1153,  0.2188,  0.0277, -0.2442, -0.2005, -0.2073,
         -0.0907,  0.1192,  0.0613,  0.0106, -0.1654,  0.0854,  0.2349,  0.0220,
         -0.1359, -0.0507,  0.0487, -0.3426,  0.2141,  0.0548,  0.0302, -0.0428,
          0.1925,  0.0710,  0.0021,  0.0956,  0.0110, -0.0648,  0.0865, -0.1772,
         -0.2910, -0.0501]], device='mps:0', grad_fn=<LinearBackward0>)


### 3. Quickly test your answer in step 2. with a batch of 512 sentences on the GPU.

In [90]:
# sentences = [sent.to(device) for sent in sents]

# Run forward pass
batch_size = 512
for i in range(0, len(sents), batch_size):
    batch_sentences = sents[i:i+batch_size]
    sentence_embeddings = glove_embeds_avg_50_dim(batch_sentences)
    print(sentence_embeddings.shape)

AttributeError: 'list' object has no attribute 'split'

### Congratulations! You almost implemented the model in the Deep Averaging Networks (DAN) paper!

# 4. Task: 
### Create a   MultiEmbedding  Module that can take two sets of indices, embed them, and concat the results. You might remember it from the previous lecture where we had to produce an embedding for "green apple" from embeddings of "green" and "apple". Your  MultiEmbedding class should work with the following test code.

In [105]:
class MultiEmbedding(nn.Module):
    
    def __init__(self, 
                 num_emb, 
                 size_emb1, 
                 size_emb2):
        super().__init__()
        self.embedding_A = nn.Embedding(num_emb, size_emb1)
        self.embedding_B = nn.Embedding(num_emb, size_emb2)
        
    def forward(self, 
                indices1, 
                indices2):
        embed_A = self.embedding_A(indices1)
        embed_B = self.embedding_B(indices2)
        # Concatenate the Embeddings
        return torch.cat((embed_A, embed_B), 
                         dim = -1)

In [106]:
# Test code: instantiate a MultiEmbedding with the sizes for each embedding. 
# For this example, you can just randomly initialize each interior embedding. 
# In a practical setting, you might support methods for initializing with 
# combinations of embeddings, such as GloVe 300d vectors and word2vec 200d 
# vectors, yielding 500d embeddings. Both embeddings share a vocabulary/range 
# of supported indices indicated by `num_emb`

NUM_EMB = 10000
SIZE_EMB1 = 300
SIZE_EMB2 = 200
BATCH_SIZE = 64
NUM_LENGTH = 10

multiemb = MultiEmbedding(NUM_EMB, 
                          SIZE_EMB1, 
                          SIZE_EMB2).to(device)

# You can then call this with a pair of indices where each value is in 0 <= i < num_emb
indices1 =  torch.randint(0, 
                          NUM_EMB, 
                          (BATCH_SIZE, NUM_LENGTH), 
                          dtype = torch.long, 
                          device = device) # long tensor of shape (batch, num_length)
indices2 =  torch.randint(0, 
                          NUM_EMB, 
                          (BATCH_SIZE, NUM_LENGTH), 
                          dtype = torch.long, 
                          device = device) # long tensor of shape (batch, num_length)
output = multiemb(indices1, 
                  indices2)
print(output.shape) # should be (batch, num_length, size_emb1 + size_emb2)

torch.Size([64, 10, 500])


# 5. Datasets and DataLoaders: 
### Read this short post on PyTorch Dataset and DataLoaders. Often in prototyping we need to generate dummy datasets to test our models. Implement a PyTorch Dataset class that generates up to  num_sentences  random sentences of length up to  max_len words. For each sentence, generate a binary label. You should be able to test your code as follows: