# Import Necessary Libraries

In [100]:
import torch
import torchtext
print(torch.__version__)
print(torchtext.__version__)

1.13.1
0.14.1


# Set device as GPU if available

In [101]:
if torch.cuda.is_available():
    dev = 'cuda'
elif torch.backends.mps.is_available():
    dev = 'mps'
else:
    dev = 'cpu'
device = torch.device(dev)    
print(f'Device: {device}')

Device: mps


# PyTorch warmup

### 1. Use torch.randn to create two tensors of size (29, 30, 32) and (32, 100)

In [102]:
tensor_a = torch.randn(29, 30, 32)
print('Tensor of Size (29, 30, 32): \n' , tensor_a)

tensor_b = torch.randn(32, 100)
print('Tensor of Size (32, 100): \n' , tensor_b)

Tensor of Size (29, 30, 32): 
 tensor([[[ 2.4883, -0.9607, -0.4936,  ...,  0.6693, -0.7385, -0.4228],
         [-1.3166, -1.2814, -0.5079,  ...,  0.0275, -0.6966, -0.0137],
         [ 1.4568,  0.8041,  0.6488,  ...,  0.1120,  0.4691, -0.6442],
         ...,
         [ 0.3687, -0.3073, -0.4400,  ...,  1.5777, -0.7677, -3.1722],
         [ 0.1493,  0.4918, -0.0713,  ..., -0.1203,  1.4416, -0.6047],
         [ 0.1150,  0.1204,  0.8325,  ...,  0.2933,  0.0103,  1.3892]],

        [[-0.2833,  2.4623,  0.4313,  ..., -0.3744,  1.3384,  0.3361],
         [ 0.6341, -2.5899, -1.5346,  ...,  1.8833,  1.5330,  2.8123],
         [ 0.9887,  0.0256, -0.1502,  ..., -0.3124, -0.2741, -1.9220],
         ...,
         [-0.3817,  1.2395,  0.2199,  ..., -0.4855,  0.6763,  0.9322],
         [ 0.7887,  0.5858, -0.0191,  ...,  1.0338, -0.6456,  0.2856],
         [ 0.0657,  0.5614, -0.7906,  ...,  0.2635, -0.9823, -1.6203]],

        [[-0.4817,  0.1315, -1.3201,  ...,  0.8710,  0.9048, -1.3712],
         [ 0.4

### 2. Use  torch.matmul  to matrix multiply the two tensors

In [103]:
product = torch.matmul(tensor_a, 
                       tensor_b)
print('Product of tensor_a and tensor_b: \n' , product)

print('Shape of Tensor: ' , product.shape)

Product of tensor_a and tensor_b: 
 tensor([[[ 10.6310,  -3.5012,  -0.2206,  ...,   9.4495,  13.3306,   8.3598],
         [ -5.7695,  -3.4139,   0.3206,  ...,  -2.8361,  -4.5913,  -6.8342],
         [ -3.9164,  -2.8580,   2.4313,  ...,  -4.2417,  -4.1108,   2.8881],
         ...,
         [  1.2043,   2.1710,  -0.2518,  ...,  -3.4719,  -5.5821,   0.8495],
         [  0.2801,   1.7620,  -3.0831,  ...,  -4.7040,  -1.3947,   0.6950],
         [ -6.4814,  -5.7364,   7.5082,  ...,  -7.7107,   1.4880,   2.2745]],

        [[  2.5742,  -2.1590,  -0.8438,  ...,   6.8380,  -1.2750,  -0.7221],
         [-13.9902,   3.1549,   8.2805,  ...,  -8.4492,  -1.1996,  -1.7942],
         [ -2.3876,  -7.6067,   1.1881,  ...,   6.5266,   6.2222,  -7.3543],
         ...,
         [ -1.0327,   0.0378,   4.1401,  ...,  -3.9587,   0.1316,   3.5204],
         [ -6.3405,   8.9789,   7.8754,  ...,  -9.0973,  -0.6199,   0.8649],
         [  4.1925,  -0.6651,   2.5484,  ...,   1.6287,   3.9758,  -4.6517]],

        

### 3. What is the difference between torch.matmul , torch.mm , torch.bmm , and torch.einsum , and the @ operator?

1. torch.matmul() -> It is a matrix multiplication function that can handle broadcasting, it can be used to perform matrix multiplication between two tensors of any shape. The function will automatically broadcast the smaller tensor to match the shape of the larger tensor, and then perform the matrix multiplication.
2. torch.mm() -> It is also a matrix multiplication function, but it is a lower level function that does not handle broadcasting. It can only be used to perform matrix multiplication between two tensors with the same number of dimensions and the last two dimensions should have the same size. It is faster than torch.matmul since it avoids broadcasting.
3. torch.bmm() -> It is used for batch matrix multiplication, it accepts three tensors of shapes (batch size, n, m), (batch size, m, p) and (batch size, n, p) to perform matrix multiplication on the last two dimensions of the input tensors.
4. torch.einsum() -> It is a more flexible function than the others and allows you to specify the indices of the tensors that you want to contract, it can also be used for many other operations like dot product, outer product, and tensor transpose.
5. @ operator -> It is a shorthand for the torch.matmul() function.

### 4. Use torch.sum on the resulting tensor, passing the optional argument of dim=1 to sum across the 1st dimension. Before you run this, can you predict the size?

In [104]:
tensor_sum = torch.sum(product, 
                       dim = 1)
print('Sum of Tensor across 1st Dimension: \n' , tensor_sum)

print('Shape of Tensor: ' , tensor_sum.shape)

Sum of Tensor across 1st Dimension: 
 tensor([[-26.3680,  -8.1909,  12.9245,  ..., -27.4859,  31.5785,   9.4467],
        [ -7.5412, -15.4592,  55.8832,  ..., -22.3710,  42.2481,  11.7929],
        [ 40.2438,  31.4988,   7.6273,  ...,  24.0534,  26.2030, -29.9862],
        ...,
        [ 28.6942,   6.3963,  46.8983,  ...,  71.9117,  -0.1161, -34.1402],
        [ 31.7517,  45.7850,   3.1688,  ...,  70.1577,  26.3011,  11.8690],
        [ 12.1463,  -6.6169,  -3.0134,  ...,  13.9262,  28.7455, -54.7362]])
Shape of Tensor:  torch.Size([29, 100])


### 5. Create a new long tensor of size  (3, 10)

In [105]:
long_tensor = torch.ones((3, 10), 
                         dtype = torch.long)
print('Long Tensor: \n' , long_tensor)

long_tensor[0, 0] = 2
long_tensor[1, 2] = 4
long_tensor[2, 4] = 6

print('Updated Long Tensor: \n' , long_tensor)

Long Tensor: 
 tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
Updated Long Tensor: 
 tensor([[2, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 4, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 6, 1, 1, 1, 1, 1]])


### 6. Use this new long tensor to index into the tensor from step 2

In [106]:
indexed_tensor = product[long_tensor]
print('Indexed Tensor: \n' , indexed_tensor)

print('Shape of Tensor: ' , indexed_tensor.shape)

Indexed Tensor: 
 tensor([[[[  6.5144,  -5.0366,   7.4834,  ...,   3.8429,   2.2695,  -0.7630],
          [ -8.4859,  -6.7342,  -0.2137,  ...,  -3.6924,   6.2722,  -2.2939],
          [ -3.2167,   3.1696,  -7.2846,  ...,   1.9399,  -4.1745,  -1.4905],
          ...,
          [  9.5965,  -0.8727,  -0.5326,  ...,   0.7845,  -1.8750,   7.3734],
          [ -3.8006,  -0.9587,  13.1253,  ...,  -0.7203,   1.2108,  -3.4721],
          [ -4.2917,  -0.2778,   7.3940,  ...,  -5.7005,   5.7263,   2.9652]],

         [[  2.5742,  -2.1590,  -0.8438,  ...,   6.8380,  -1.2750,  -0.7221],
          [-13.9902,   3.1549,   8.2805,  ...,  -8.4492,  -1.1996,  -1.7942],
          [ -2.3876,  -7.6067,   1.1881,  ...,   6.5266,   6.2222,  -7.3543],
          ...,
          [ -1.0327,   0.0378,   4.1401,  ...,  -3.9587,   0.1316,   3.5204],
          [ -6.3405,   8.9789,   7.8754,  ...,  -9.0973,  -0.6199,   0.8649],
          [  4.1925,  -0.6651,   2.5484,  ...,   1.6287,   3.9758,  -4.6517]],

         [[ 

### 7. Use  torch.mean  to average across the last dimension in the tensor from step 6

In [107]:
mean_tensor = torch.mean(indexed_tensor, 
                         dim = 3)
print(mean_tensor)

print('Shape of Tensor: ' , mean_tensor.shape)

tensor([[[ 8.7892e-02,  5.0581e-01, -3.4461e-02, -4.1773e-01,  1.7341e-02,
          -4.7851e-01,  6.9303e-01, -1.7999e-01, -7.4158e-02,  4.0920e-01,
           5.1396e-01, -1.2904e-01, -3.7786e-01, -3.6777e-02,  1.2503e+00,
           5.4853e-01,  5.3842e-01,  3.6802e-01, -7.5418e-02, -3.9743e-01,
          -7.2443e-01,  3.2765e-02, -2.1954e-01,  2.0872e-01, -7.8701e-01,
           1.3227e+00,  2.1916e-01,  6.9837e-02,  2.1579e-01,  1.3233e-01],
         [ 6.9553e-01, -9.8286e-01, -1.3238e-02, -4.1150e-02, -4.8392e-02,
           1.1633e+00, -7.0964e-01, -7.5471e-02,  1.0129e-01, -2.7180e-01,
          -1.4452e-02,  3.4041e-01,  3.5615e-01,  4.5030e-01,  3.3111e-01,
          -2.7080e-02,  7.3014e-01,  7.3225e-02, -4.3879e-01, -1.2075e+00,
          -4.5055e-02,  8.3584e-02, -2.8191e-05, -2.7348e-01,  4.2732e-01,
          -2.3573e-01,  4.3454e-01,  2.8898e-01,  2.2725e-01,  9.5347e-01],
         [ 6.9553e-01, -9.8286e-01, -1.3238e-02, -4.1150e-02, -4.8392e-02,
           1.1633e+00, 

### 8. Redo step 2. on the GPU and compare results from step 2

In [108]:
tensor_a_cuda = tensor_a.to(device = device)
tensor_b_cuda = tensor_b.to(device = device)
product_gpu = torch.matmul(tensor_a, 
                           tensor_b)
print('Product of tensor_a and tensor_b on GPU: \n' , product_gpu)

print('Shape of Tensor: ' , product_gpu.shape)

Product of tensor_a and tensor_b on GPU: 
 tensor([[[ 10.6310,  -3.5012,  -0.2206,  ...,   9.4495,  13.3306,   8.3598],
         [ -5.7695,  -3.4139,   0.3206,  ...,  -2.8361,  -4.5913,  -6.8342],
         [ -3.9164,  -2.8580,   2.4313,  ...,  -4.2417,  -4.1108,   2.8881],
         ...,
         [  1.2043,   2.1710,  -0.2518,  ...,  -3.4719,  -5.5821,   0.8495],
         [  0.2801,   1.7620,  -3.0831,  ...,  -4.7040,  -1.3947,   0.6950],
         [ -6.4814,  -5.7364,   7.5082,  ...,  -7.7107,   1.4880,   2.2745]],

        [[  2.5742,  -2.1590,  -0.8438,  ...,   6.8380,  -1.2750,  -0.7221],
         [-13.9902,   3.1549,   8.2805,  ...,  -8.4492,  -1.1996,  -1.7942],
         [ -2.3876,  -7.6067,   1.1881,  ...,   6.5266,   6.2222,  -7.3543],
         ...,
         [ -1.0327,   0.0378,   4.1401,  ...,  -3.9587,   0.1316,   3.5204],
         [ -6.3405,   8.9789,   7.8754,  ...,  -9.0973,  -0.6199,   0.8649],
         [  4.1925,  -0.6651,   2.5484,  ...,   1.6287,   3.9758,  -4.6517]],

 

### 9. Write a pure PyTorch program to compute the value of $\sqrt{2}$ up to 4 decimal places without using the square root or other math functions from any of the libraries. 
### Hint: Notice that the answer is the (positive) root of the equation, $$𝑥^2 −2 = 0$$ 
### To find the root, you might want to use 'Newton's Method': $$𝑥_{𝑛+1} = 𝑥_{𝑛} − \frac{𝑓(𝑥)}{𝑓′(𝑥)}$$

In [121]:
# Function f(x)
def f(x):
    return x**2 - 2

# Derivative of f(x)
def f_prime(x):
    return 2*x

# Initial Guess = 1.0
x = torch.tensor([1.0], 
                 requires_grad = True)

# Number of Iterations
n = 10

# Newton's Method
for i in range(n):
    x.data = x - f(x) / f_prime(x)

# Print the final approximation to 4 decimal places
print(round(x.item(), 4))

1.4142


# Fail-fast prototyping

When building neural networks, you want things to either work or fail fast. Long iteration loops are 
the worst enemy of a machine learning practitioner. \
For e.g., while writing code, you might want to incrementally test your code by doing something 
like this:

batch_size = 32 \
num_features = 512 \
embedding_size = 16

\# construct a dummy input \
x = torch.randn(batch_size, num_features)

\# we want to project the input to embedding_size \
fc = torch.nn.Linear(num_features, embedding_size)

\# test if that works \
print(fc(x).shape)

# Fail-fast exercises

### 1. [Glove](https://nlp.stanford.edu/projects/glove/) has 300 dimension embeddings. Design an nn.Module that takes a sentence of max_len words, tokenizes words by spaces, represents the sentence by averaging the glove embeddings of constituent words. What is the shape of the resulting sentence embedding? When you implement this, you will need to make some assumptions. What are they?

In [109]:
# Load GloVe Embeddings
from torchtext.vocab import GloVe

GLOVE_DIM = 300
glove = GloVe(name = '840B', 
              dim = GLOVE_DIM)

print(f'Loaded {len(glove.itos)} words present in GloVe')

embeddings_tensor = glove.vectors
embeddings_tensor = embeddings_tensor.to(device = device)

Loaded 2196017 words present in GloVe


In [110]:
# Generate 512 sentences
NUM_SENT = 512
sents = list()
for i in range(NUM_SENT):
    sents.append('This is the quest zero and it has a deadline this Sunday March 29')
print(len(sents))

512


In [111]:
import torch.nn as nn

class GloveEmbeddingAvg(nn.Module):
    
    def __init__(self, max_len):
        super().__init__()
        self.max_len = max_len
        self.embedding = nn.Embedding.from_pretrained(embeddings_tensor)
        
    def forward(self, 
                sent):
        # Tokenize the sentence by spaces
        tokens = sent.split(' ')[:self.max_len]
        # Get idx of each token from the GloVe dictionary
        glove_dict_indexes = [glove.stoi[token] for token in tokens]
        # Convert it into Tensor
        glove_dict_indexes = torch.tensor(glove_dict_indexes, 
                                          device = device)
        # Get Word Embeddings for all tokens
        word_embeds = self.embedding(glove_dict_indexes) # [MAX_LEN, GLOVE_DIM]
        # Sentence Embedding = Average of Word Embeddings
        sent_embeds = word_embeds.mean(dim = 0) # [GLOVE_DIM]
        # Reshape Sentence Embedding as a 2D Tensor
        return sent_embeds.view(1, -1) # [1, GLOVE_DIM]

MAX_LEN = 10
glove_embeds_avg = GloveEmbeddingAvg(MAX_LEN).to(device)

print(glove_embeds_avg(sents[0]).shape)

torch.Size([1, 300])


### 2. How will you modify step 1. so that the sentence embeddings are in $R^{50}$ ?
BONUS: Can you think of more than one way to do this? What are the implications of each method?

In [112]:
class GloveEmbeddingAvg_50_Dim(nn.Module):
    
    def __init__(self, max_len):
        super().__init__()
        self.max_len = max_len
        self.embedding = nn.Embedding.from_pretrained(embeddings_tensor)
        self.fc = nn.Linear(GLOVE_DIM, 50)
        
    def forward(self, 
                x):
        # Slice each sentence to Max Length
        x = x[:, :self.max_len]
        # Get Word Embeddings for all tokens
        word_embeds = self.embedding(x) # [BATCH_SIZE, MAX_LEN, GLOVE_DIM]
        # Sentence Embedding = Average of Word Embeddings
        sent_embeds = word_embeds.mean(dim = 0) # [MAX_LEN, GLOVE_DIM]
        # Linear Layer to reduce Sentence Embedding Dimension to 50
        return self.fc(sent_embeds) # [MAX_LEN, 50]

MAX_LEN = 10
glove_embeds_avg_50_dim = GloveEmbeddingAvg_50_Dim(MAX_LEN).to(device)

### 3. Quickly test your answer in step 2. with a batch of 512 sentences on the GPU.

In [113]:
# Tokenize a Sentence
def tokenize(sent):
    # Tokenize the sentence by spaces
    tokens = sent.split(' ')
    # Get idx of each token from the GloVe dictionary
    glove_dict_indexes = [glove.stoi[token] for token in tokens]
    return glove_dict_indexes

# Create Tokenized Sentence Corpus
tokenized_sents = list()
for sent in sents:
    tokenized_sents.append(tokenize(sent))
tokenized_sents = torch.tensor(tokenized_sents, 
                               device = device)

# Run forward pass
BATCH_SIZE = 512
for i in range(0, len(tokenized_sents), BATCH_SIZE):
    batch = tokenized_sents[i:i+BATCH_SIZE]
    sentence_embeddings = glove_embeds_avg_50_dim(batch)
    print(sentence_embeddings.shape)

torch.Size([10, 50])


### Congratulations! You almost implemented the model in the Deep Averaging Networks (DAN) paper!

# 4. Task: 
### Create a   MultiEmbedding  Module that can take two sets of indices, embed them, and concat the results. You might remember it from the previous lecture where we had to produce an embedding for "green apple" from embeddings of "green" and "apple". Your  MultiEmbedding class should work with the following test code.

In [114]:
class MultiEmbedding(nn.Module):
    
    def __init__(self, 
                 num_emb, 
                 size_emb1, 
                 size_emb2):
        super().__init__()
        self.embedding_A = nn.Embedding(num_emb, size_emb1)
        self.embedding_B = nn.Embedding(num_emb, size_emb2)
        
    def forward(self, 
                indices1, 
                indices2):
        embed_A = self.embedding_A(indices1)
        embed_B = self.embedding_B(indices2)
        # Concatenate the Embeddings
        return torch.cat((embed_A, embed_B), 
                         dim = -1)

In [115]:
# Test code: instantiate a MultiEmbedding with the sizes for each embedding. 
# For this example, you can just randomly initialize each interior embedding. 
# In a practical setting, you might support methods for initializing with 
# combinations of embeddings, such as GloVe 300d vectors and word2vec 200d 
# vectors, yielding 500d embeddings. Both embeddings share a vocabulary/range 
# of supported indices indicated by `num_emb`

NUM_EMB = 10000
SIZE_EMB1 = 300
SIZE_EMB2 = 200
BATCH_SIZE = 64
NUM_LENGTH = 10

multiemb = MultiEmbedding(NUM_EMB, 
                          SIZE_EMB1, 
                          SIZE_EMB2).to(device)

# You can then call this with a pair of indices where each value is in 0 <= i < num_emb
indices1 =  torch.randint(0, 
                          NUM_EMB, 
                          (BATCH_SIZE, NUM_LENGTH), 
                          dtype = torch.long, 
                          device = device) # long tensor of shape (batch, num_length)
indices2 =  torch.randint(0, 
                          NUM_EMB, 
                          (BATCH_SIZE, NUM_LENGTH), 
                          dtype = torch.long, 
                          device = device) # long tensor of shape (batch, num_length)
output = multiemb(indices1, 
                  indices2)
print(output.shape) # should be (batch, num_length, size_emb1 + size_emb2)

torch.Size([64, 10, 500])


# 5. Datasets and DataLoaders: 
### Read this short post on PyTorch Dataset and DataLoaders. Often in prototyping we need to generate dummy datasets to test our models. Implement a PyTorch Dataset class that generates up to  num_sentences  random sentences of length up to  max_len words. For each sentence, generate a binary label. You should be able to test your code as follows:

In [116]:
class DeepAveragingNetwork(nn.Module):
    
    def __init__(self, max_len):
        super().__init__()
        self.max_len = max_len
        self.embedding = nn.Embedding.from_pretrained(embeddings_tensor)
        self.fc = nn.Linear(GLOVE_DIM, 50)
        
    def forward(self, 
                sent):
        # Tokenize the sentence by spaces
        tokens = sent.split(' ')[:self.max_len]
        # Get idx of each token from the GloVe dictionary
        glove_dict_indexes = [glove.stoi[token] for token in tokens]
        # Convert it into Tensor
        glove_dict_indexes = torch.tensor(glove_dict_indexes, 
                                          device = device)
        # Get Word Embeddings for all tokens
        word_embeds = self.embedding(glove_dict_indexes) # [MAX_LEN, GLOVE_DIM]
        # Sentence Embedding = Average of Word Embeddings
        sent_embeds = word_embeds.mean(dim = 0) # [GLOVE_DIM]
        # Linear Layer to reduce Sentence Embedding Dimension to 50
        return self.fc(sent_embeds.view(1, -1)) # [1, 50]

model = DeepAveragingNetwork(MAX_LEN).to(device)

In [117]:
import random
from torch.utils.data import Dataset

class DummySentenceLabelDataset(Dataset):
    """
    A simple dataset that generates random sentences and labels for each sentence.
    Args:
        num_sentences (int): The number of sentences to generate.
        max_len (int): The maximum length of each sentence.
    """
    def __init__(self, 
                 num_sentences, 
                 max_len):
        """
        Initializes the dataset with the given number of sentences and maximum sentence length.
        Generates the sentences and labels using the generate_sents() and generate_labels() methods.
        """
        self.num_sentences = num_sentences
        self.max_len = max_len
        self.sents = self.generate_sents()
        self.labels = self.generate_labels()
        
    def __len__(self):
        """
        Returns the number of sentences in the dataset.
        """
        return self.num_sentences
        
    def __getitem__(self, 
                    idx):
        """
        Returns the sentence and label at the given index.
        """
        return self.sents[idx], self.labels[idx]
    
    def get_random_sent(self, word_list):
        """
        Generates a random sentence using the given list of words.
        Args:
            word_list (list): A list of words to choose from when generating the sentence.
        Returns:
            str: A sentence composed of randomly chosen words from the given list.
        """
        sent = ''
        for i in range(self.max_len):
            word = random.choice(word_list)
            sent += word + ' '
        return sent
    
    def generate_sents(self):
        """
        Generates a list of random sentences.
        Uses the get_random_sent() method to generate each sentence.
        Returns:
            list: A list of randomly generated sentences.
        """
        word_list = ['Hello', 'World', 'Python', 'Function', 'Random', 'Sentence', 
                     'List', 'Words', 'Generates', '20', 'Example', 'Simple', 'Program', 
                     'Easy', 'Understand', 'Learn', 'Code', 'Implement', 'Execute', 'Run', 
                     'Brazil', 'India', 'Chat', 'India', 'Golden', 'State', 'Warriors']
        sents = list()
        for i in range(self.num_sentences):
            sent = self.get_random_sent(word_list)
            sents.append(sent)
        return sents
    
    def generate_labels(self):
        """
        Generates a list of random labels (0 or 1) for each sentence.
        Returns:
            list: A list of randomly generated labels.
        """
        labels = list()
        for i in range(self.num_sentences):
            labels.append(random.randint(0, 1))
        return labels

NUM_SENTENCES = 10
MAX_LEN = 20
dataset = DummySentenceLabelDataset(num_sentences = NUM_SENTENCES, 
                                    max_len = MAX_LEN)

#### Let's measure the error rate for one epoch

In [118]:
error = 0.0
for sentence, label in dataset:
  print(f'Sentence: {sentence},\nLabel: {label}')
  prediction = model(sentence)
  error += abs(prediction - label)
print('==================================================================')  
print(f'Error rate: {error/len(dataset)}')

Sentence: Execute Golden Implement State 20 Warriors Simple India Sentence Program List Code Random Program 20 India Generates Random India Function ,
Label: 1
Sentence: Sentence Code Understand Words Implement Warriors Run India Chat Golden India Brazil Words Warriors Warriors Run Random Simple Understand Run ,
Label: 1
Sentence: Program Easy Function Sentence Function Program Words Simple Warriors Chat Words Understand Code Sentence Golden Learn Easy Sentence India Understand ,
Label: 0
Sentence: Understand India Words Random Function World 20 Chat Execute State Random Words Function Example India Python Golden World Warriors Program ,
Label: 1
Sentence: Random Brazil Example Implement Brazil Function State Program India Function Function State Golden Code Execute Execute Golden Example World Golden ,
Label: 0
Sentence: World Learn 20 Easy Golden Simple Python Golden Sentence Generates Brazil Easy World Easy State World Simple Words Generates List ,
Label: 0
Sentence: India Execute L